### ISSUE TITLE
content-length - body + CRLF

### ISSUE THREAD

**Issue by AuroraSloan** [rnittaBadCommit/webserv#11]
content-lengthの場合、body後もCRLFがあれば、特にwebservの行動は正しくないかもしれないです

**Comment by oooooorriiiii** [comment]
I would also like to know more about `Content-Length`. I think this topic is also related to issue #9 . 
I would be grateful if @AuroraSloan  could tell me what you know about `Content-Length`.
Thank you.
https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2

**Comment by AuroraSloan** [comment]
@oooooorriiiii 
ごめんなさいけど、、HTTPリクエストの送信方法について、私の誤解でした。問題ありません。しかし、content-lengthについては説明します。
content-lengthはボディのバイト数です(decimalの）。もしボディがあってもcontent-lengthもtransfer-encodingもなければ、400として送ります。また、実際のボディのサイズがcontent-lengthと合っていない場合も、400として送くるべきだと思います。
transfer-encodingとcontent-lengthの両方がある場合、400として送くり、パース時にcontent-lengthを消します。
content-length ヘッダはカンマ区切りのリストにはできません。例えば "content-length:42, 42"。
または、content-length一つ以上、違う番号があればも400になります。
"content-length:42 "
"content-length:37 "
しかし、同じ番号を持つ複数のcontent-lengthがある場合、それは問題なく、余分なcontent-lengthヘッダを無視することになります。

その情報はぜんぶリクエストに関連するとおもいます。しかし、RFCには、特にサーバーレスポンスに関連する情報がもっとあると思っています。もし、理解するための手助けが必要であれば、教えてください。

**Comment by oooooorriiiii** [comment]
Thank you very much.
Your explanation helped my understanding.😀
