### ISSUE TITLE
Response is only sent after timeout

### ISSUE THREAD

**Issue by AuroraSloan** [rnittaBadCommit/webserv#41]
socketのkeep_connect_time_lenは、接続はあるがメッセージのこないときに待ち続ける時間です。
指定された時間内にメッセージを受信しない場合、ソケットはタイムアウトして閉じられます。
httpprocessの現在実行はtimeoutを終わったらだけresponseを送っていそうとおもいます。これでなくすぐにresponseを送るほうがいいと思います。
今の状態timeoutの時間は10秒ぐらいです（debugのため）でも後は、120秒ぐらいにすると思います。
@oooooorriiiii 
私は今httpmethod httpprocessをよく読んでみていますので、私もその問題を探します

**Comment by oooooorriiiii** [comment]
- get, put, post, and delete do not check for timeouts. (I didn't think it was necessary. If necessary, I will implement it.)
- CGI timeouts are not checked. (This is necessary. I just haven't done it yet.)

**Comment by AuroraSloan** [comment]
yes, I found that get was returning immediately, but the client was waiting for more message for some reason. So it didn't display the message until we disconnect.
I found the problem just now :') content-length is spelled incorrectly. If you fix the spelling, then the behavior will be correct.
Let's both double check the header spellings
https://github.com/rnittaBadCommit/webserv/blob/bffa6bd567b2dd1b240509d58e66d15538645137/srcs/httpMethod/HTTPMethod.cpp#L168

**Comment by oooooorriiiii** [comment]
Ugh, is that my typo? Sorry. Thanks for figuring out what caused it.
